#!/usr/bin/env bash
set -euo pipefail
#
# init-env.sh — interactive .env generator for the Ferdinand stack.
#
# Prompts for the public-facing settings (domain, basic_auth user/pass, admin
# username) and auto-generates the cryptographic material (session key, bcrypt
# hash). Writes /opt/ferdinand/.env (or $PWD/.env) with chmod 600.
#
# Re-running is safe: an existing .env is renamed to .env.bak.<timestamp>
# before the new one is written, so old values can be recovered.
#
# Secrets (password, session key, bcrypt hash) are NEVER printed to stdout.

REPO_DIR="${FERDINAND_INSTALL_DIR:-/opt/ferdinand}"
ENV_FILE="${REPO_DIR}/.env"

log() {
    echo "[init-env] $*"
}

err() {
    echo "[init-env] ERROR: $*" >&2
}

if [[ ! -d "$REPO_DIR" ]]; then
    err "repo dir not found: $REPO_DIR"
    err "run bootstrap-vps.sh first, or set FERDINAND_INSTALL_DIR."
    exit 1
fi

cd "$REPO_DIR"

if [[ ! -f docker-compose.yml ]]; then
    err "docker-compose.yml not in $REPO_DIR — wrong directory?"
    exit 1
fi

# Backup existing .env (if any) before overwriting.
if [[ -f "$ENV_FILE" ]]; then
    backup="${ENV_FILE}.bak.$(date +%Y%m%d-%H%M%S)"
    cp -p "$ENV_FILE" "$backup"
    chmod 600 "$backup"
    log "existing .env backed up to: $backup"
fi

# Sanity-check tooling we'll need.
if ! command -v openssl >/dev/null 2>&1; then
    err "openssl not found — install it first (apt-get install -y openssl)."
    exit 1
fi
if ! command -v docker >/dev/null 2>&1; then
    err "docker not found — run bootstrap-vps.sh first."
    exit 1
fi

prompt_value() {
    # prompt_value <var-name> <prompt-text> [default]
    local __var="$1"
    local __prompt="$2"
    local __default="${3:-}"
    local __input=""

    while [[ -z "$__input" ]]; do
        if [[ -n "$__default" ]]; then
            read -r -p "$__prompt [$__default]: " __input
            __input="${__input:-$__default}"
        else
            read -r -p "$__prompt: " __input
        fi
        if [[ -z "$__input" ]]; then
            echo "  (value required, please try again)" >&2
        fi
    done

    printf -v "$__var" '%s' "$__input"
}

prompt_secret() {
    # prompt_secret <var-name> <prompt-text>
    # Reads twice (hidden) and verifies they match.
    local __var="$1"
    local __prompt="$2"
    local __first=""
    local __second=""

    while true; do
        read -r -s -p "$__prompt: " __first
        echo ""
        if [[ -z "$__first" ]]; then
            echo "  (value required, please try again)" >&2
            continue
        fi
        read -r -s -p "$__prompt (confirm): " __second
        echo ""
        if [[ "$__first" == "$__second" ]]; then
            break
        fi
        echo "  values did not match, please try again" >&2
    done

    printf -v "$__var" '%s' "$__first"
}

log "Configure Ferdinand .env (Ctrl-C to abort)."
echo ""

prompt_value DOMAIN "Public domain (DNS A record points here, e.g. anki.example.com)"
prompt_value ACME_EMAIL "Let's Encrypt contact email (optional, blank to skip)" ""
prompt_value ANKI_ADMIN_USERNAME "Anki admin username (only this user can hit /api/admin/*; blank to disable)" ""
prompt_value BASIC_AUTH_USER "HTTP basic_auth username for the Caddy gate"
prompt_secret BASIC_AUTH_PASS "HTTP basic_auth password (will be bcrypt-hashed, stored hashed only)"
prompt_value ANKI_IMPORT_MAX_BYTES "Max apkg upload size in bytes" "104857600"

log "generating FERDINAND_SESSION_KEY (openssl rand -base64 64)..."
SESSION_KEY="$(openssl rand -base64 64 | tr -d '\n')"

log "generating BASIC_AUTH_HASH via 'docker run --rm caddy:2 caddy hash-password'..."
# Pass the plaintext via env so it doesn't appear in argv / process list.
BASIC_AUTH_HASH="$(BASIC_AUTH_PASS="$BASIC_AUTH_PASS" docker run --rm \
    -e BASIC_AUTH_PASS \
    caddy:2 \
    sh -c 'caddy hash-password --plaintext "$BASIC_AUTH_PASS"' | tr -d '\r\n')"

if [[ -z "$BASIC_AUTH_HASH" ]]; then
    err "caddy hash-password produced empty output — aborting."
    exit 1
fi

# Write .env. bcrypt hashes (and the base64 session key) can contain `$` and
# other shell-meta chars, so each value is single-quoted. Single-quoted
# strings are literal in docker compose env-file parsing.
umask 077
{
    echo "# Auto-generated by deploy/scripts/init-env.sh"
    echo "# $(date -Is)"
    echo "# Do NOT commit this file — it is .gitignored / .dockerignored."
    echo ""
    echo "# Caddy / TLS"
    echo "DOMAIN='${DOMAIN}'"
    echo "ACME_EMAIL='${ACME_EMAIL}'"
    echo ""
    echo "# HTTP basic_auth (Caddy gate)"
    echo "BASIC_AUTH_USER='${BASIC_AUTH_USER}'"
    echo "BASIC_AUTH_HASH='${BASIC_AUTH_HASH}'"
    echo ""
    echo "# anki_server"
    echo "FERDINAND_SESSION_KEY='${SESSION_KEY}'"
    echo "ANKI_ADMIN_USERNAME='${ANKI_ADMIN_USERNAME}'"
    echo "ANKI_IMPORT_MAX_BYTES='${ANKI_IMPORT_MAX_BYTES}'"
    echo ""
    echo "# Optional first-boot seed user (idempotent — leave blank to skip)"
    echo "FERDINAND_SEED_USER=''"
    echo "FERDINAND_SEED_PASSWORD=''"
} > "$ENV_FILE"

chmod 600 "$ENV_FILE"

# Scrub the in-memory secrets just in case anything later in this script
# accidentally echoes the environment.
unset BASIC_AUTH_PASS SESSION_KEY BASIC_AUTH_HASH

log "Wrote .env (chmod 600). Next: docker compose up -d"
